# Generated by Django 4.0.5 on 2022-07-21 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipoDeSalas', models.CharField(choices=[('g', 'Génesis'), ('p', 'Piscis'), ('h1', 'Híbrida_Tipo_1'), ('h2', 'Híbrida_Tipo_2'), ('p', 'Pile'), ('a3', 'A3')], default='p', max_length=2)),
                ('piso', models.IntegerField(default=1)),
                ('capacidad', models.PositiveIntegerField()),
                ('estadoSala', models.CharField(choices=[('O', 'Operativa'), ('M', 'Mantención'), ('B', 'Baja')], default='Operativa', max_length=1)),
                ('wifi', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='No', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, unique=True)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telon', models.CharField(choices=[('a', 'Manual'), ('b', 'Mecanico')], default='a', max_length=1)),
                ('estadoTelon', models.CharField(choices=[('O', 'Operativo'), ('M', 'Mantención'), ('B', 'Baja')], default='Operativo', max_length=1)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salas.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Sonido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadParlantes', models.PositiveIntegerField()),
                ('tipoSistemaSonido', models.CharField(choices=[('1', 'Amplificador'), ('2', 'SubWoofer'), ('3', 'Parlantes')], default='Amplificador', max_length=1)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salas.sala')),
            ],
        ),
        migrations.AddField(
            model_name='sala',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salas.sede'),
        ),
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=20)),
                ('horasLampara', models.PositiveIntegerField()),
                ('fechaInstalacion', models.DateField()),
                ('controlRemoto', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='Si', max_length=1)),
                ('estadoProyector', models.CharField(choices=[('O', 'Operativo'), ('M', 'Mantención'), ('B', 'Baja')], default='Operativo', max_length=1)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salas.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=20)),
                ('fechaInstalacion', models.DateField()),
                ('tamaño', models.CharField(choices=[('a', 17), ('b', 18), ('c', 19), ('d', 20), ('f', 21), ('g', 22)], default='a', max_length=1)),
                ('estadoMonitor', models.CharField(choices=[('O', 'Operativo'), ('M', 'Mantención'), ('B', 'Baja')], default='Operativo', max_length=1)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salas.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sistemaOperativo', models.CharField(max_length=20, verbose_name='Sistema Operativo')),
                ('ip', models.CharField(max_length=50, verbose_name='Dirección IP')),
                ('mac', models.CharField(max_length=20, verbose_name='Dirección MAC')),
                ('mascaraSubRed', models.CharField(max_length=50, verbose_name='Máscara SubRed')),
                ('fechaInstalacion', models.DateField(verbose_name='Fecha Instalación')),
                ('procesador', models.CharField(max_length=50, verbose_name='Procesador')),
                ('memoriRam', models.CharField(max_length=50, verbose_name='Memoria Ram')),
                ('estadoPC', models.CharField(choices=[('O', 'Operativo'), ('M', 'Mantención'), ('B', 'Baja')], default='Operativo', max_length=1, verbose_name='Estado')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salas.sala')),
            ],
        ),
    ]
