# Generated by Django 4.0.5 on 2022-07-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='cableProfesor',
            field=models.CharField(choices=[('H', 'HDMI'), ('V', 'VGA')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='sala',
            name='tipoCaja',
            field=models.CharField(choices=[('p', 'Pared'), ('m', 'Meson'), ('n', 'No tiene')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='computador',
            name='fechaInstalacion',
            field=models.DateField(blank=True, verbose_name='Fecha Instalación'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='ip',
            field=models.CharField(max_length=50, unique=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='mac',
            field=models.CharField(max_length=20, unique=True, verbose_name='Dirección MAC'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='mascaraSubRed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Máscara Sub-Red'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='fechaInstalacion',
            field=models.DateField(blank=True, verbose_name='Fecha Instalación'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='modelo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='serie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipoDeSalas',
            field=models.CharField(choices=[('g', 'Génesis'), ('p', 'Piscis'), ('h1', 'Híbrida_Tipo_1'), ('h2', 'Híbrida_Tipo_2'), ('pi', 'Pile'), ('a3', 'A3')], default='p', max_length=2),
        ),
        migrations.AlterField(
            model_name='sonido',
            name='tipoSistemaSonido',
            field=models.CharField(choices=[('1', 'Amplificador'), ('2', 'SubWoofer'), ('3', 'Parlantes'), ('4', 'No Posee')], default='Amplificador', max_length=1),
        ),
    ]
